import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import { cn } from "@/lib/utils";
import Providers from "@/components/providers";
import { GeistSans } from 'geist/font/sans';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={cn(
          GeistSans.className,
          "container w-full md:w-4/5 lg:w-4/6 xl:w-3/6 mx-auto mb-24 md:mb-32"
        )}
      >
        <Providers>
          <Header></Header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
